services:  
  xfe-1:
    image: docker.io/dyrnq/doris:3.0.6.2
    restart: always
    hostname: xfe-1
    volumes:
      - xfe-1-log:/opt/apache-doris/fe/log
      - xfe-1-doris-meta:/opt/apache-doris/fe/doris-meta
      - xbe-1-log:/opt/apache-doris/be/log
      - xbe-1-storage:/opt/apache-doris/be/storage
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - RUN_MODE=standalone
      - |
        DORIS_FE_PROPERTIES=
        sys_log_level: WARN
        log_roll_size_mb: 128
      - |
        DORIS_BE_PROPERTIES=
        sys_log_level: WARNING
        mem_limit: 89%
        log_level: 2
    ports:
      - 38030:8030
      - 39030:9030
    networks:
      doris-network:
volumes:
  xfe-1-doris-meta:
  xfe-1-log:
  xbe-1-storage:
  xbe-1-log:
networks:
  doris-network:
    external: true

